name: intern_weather
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  location: ^7.0.0
  shared_preferences: ^2.3.2
  flutter_bloc: ^8.1.6
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  fpdart: ^1.1.0
  http: ^1.2.2
  weather: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/gif/
    - assets/icon/
    - assets/fonts/
